scene-mesh:
  # 基础设施配置
  infrastructure:
    flink-web:
      host: 127.0.0.1
      port: 8081
    redis:
      host: localhost
      port: 6379
    message:
      batch-size: 10
      timeout-seconds: 1
  environment:
    name: dev
  # 主题配置
  topics:
    inbound-events: inbound_events
    matched-result: matched_result
    outbound-actions: outbound_actions
  # AI配置
  ai:
    provider:
      zhipu:
        api-key: 58245a200b71437bbece2b85c71c844a.uJKQJvMhutDrPQPE
    mcp:
      server:
        url: http://localhost:9001

  # 消息类配置
  message-classes:
    event: com.scene.mesh.model.event.Event
    scene-matched-result: com.scene.mesh.engin.model.SceneMatchedResult

  # api client
  api-client:
    urls:
      product: http://localhost:8082/api/entities/objects/product/?withReference=true
      llm: http://localhost:8082/api/entities/objects/languageModelProvider/?withReference=true
      mcpserver: http://localhost:8082/api/entities/objects/mcpService/?withReference=true